name: Docker CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: pip install -r requirements.txt
             pip install pytest

      - name: Run Tests
        run: pytest

      - name: Build Docker Image
        run: docker build -t ml-devops-demo .

      - name: Run Container
        run: docker run -d -p 5000:5000 ml-devops-demo

      - name: Deploy Container
        run:  docker run ml-devops-demo